import "./globals.css";
import Providers from "./provider";

export const metadata = {
  title: "Reddit with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto w-full max-w-[640px]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
